[package]
name = "extract"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "rustls-tls"] }
scraper = "0.15"
clap = { version = "4.1", features = ["derive"] }
